# Generated by Django 4.0.5 on 2022-07-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cprofile', '0002_company_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cprofile.company'),
        ),
        migrations.AlterField(
            model_name='companycontext',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cprofile.company'),
        ),
    ]
