# Generated by Django 4.0.5 on 2022-07-22 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cprofile', '0003_alter_companyaddress_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
