# Generated by Django 4.0.5 on 2022-08-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofile', '0004_alter_company_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(default='John Wick', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='gst_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
