# Generated by Django 4.0.5 on 2022-08-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_zoho_client_id_client_zoho_client_secret_and_more'),
        ('cprofile', '0005_company_contact_person_alter_company_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='esic_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry_name',
            field=models.CharField(choices=[('agency_sales_housing', 'Agency & Sales Housing'), ('art_and_design', 'Art & Design'), ('automation', 'Automation'), ('construction', 'Construction'), ('cosulting', 'Consulting'), ('consumer_packaged_goods', 'Consumer Packaged Goods'), ('education', 'Education'), ('engineering', 'Engineering'), ('entertainment', 'Entertainment'), ('financial_services', 'Financial Services'), ('food_services', 'Food Services (Restaurants/Fast Food)'), ('gaming', 'Gaming'), ('government', 'Government'), ('healthcare', 'Health Care'), ('interior_design', 'Interior Design'), ('legal', 'Legal'), ('manufacturing', 'Manufacturing'), ('marketing', 'Marketing'), ('mining_and_logistics', 'Mining and Logistics'), ('non_profit', 'Non-Profit'), ('publishing_and_media', 'Publishing and Web Media'), ('real_estate', 'Real Estate'), ('retail', 'Retail (E-Commerce and Retails)'), ('services', 'Services'), ('technology', 'Technology'), ('telecommunications', 'Telecommunications'), ('travel_hospitality', 'Travel/Hospitality')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pf_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='country',
            field=models.CharField(default='India', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='state',
            field=models.CharField(choices=[('maharashtra', 'Maharashtra '), ('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('delhi', 'Delhi'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jammu_and_kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal')], max_length=30),
        ),
    ]
