# Generated by Django 4.0.5 on 2022-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cprofile', '0006_alter_company_client_alter_company_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='industry_name',
            field=models.CharField(choices=[('agency_sales_housing', 'Agency & Sales Housing'), ('art_and_design', 'Art & Design'), ('automation', 'Automation'), ('construction', 'Construction'), ('consulting', 'Consulting'), ('consumer_packaged_goods', 'Consumer Packaged Goods'), ('education', 'Education'), ('engineering', 'Engineering'), ('entertainment', 'Entertainment'), ('financial_services', 'Financial Services'), ('food_services', 'Food Services (Restaurants/Fast Food)'), ('gaming', 'Gaming'), ('government', 'Government'), ('healthcare', 'Health Care'), ('interior_design', 'Interior Design'), ('legal', 'Legal'), ('manufacturing', 'Manufacturing'), ('marketing', 'Marketing'), ('mining_and_logistics', 'Mining and Logistics'), ('non_profit', 'Non-Profit'), ('publishing_and_media', 'Publishing and Web Media'), ('real_estate', 'Real Estate'), ('retail', 'Retail (E-Commerce and Retails)'), ('services', 'Services'), ('technology', 'Technology'), ('telecommunications', 'Telecommunications'), ('travel_hospitality', 'Travel/Hospitality')], max_length=100),
        ),
    ]
