# Generated by Django 4.0.5 on 2022-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(blank=True, max_length=500)),
                ('raisedOn', models.DateTimeField(auto_now_add=True)),
                ('taxType', models.CharField(choices=[('income_tax', 'Income Tax'), ('gst', 'GST'), ('other_taxes', 'Other Taxes')], default='Income Tax', max_length=20)),
                ('dueDate', models.DateField()),
            ],
        ),
    ]
