# Generated by Django 4.0.5 on 2022-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0003_itquarterlystatus_rename_taxalert_incometaxalert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmonthlystatus',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('action_required', 'Client Action Required'), ('quality_check', 'Quality Check'), ('done', 'Completed')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='itquarterlystatus',
            name='paymentStatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('action_required', 'Client Action Required'), ('quality_check', 'Quality Check'), ('done', 'Completed')], default='Pending', max_length=30),
        ),
    ]
