# Generated by Django 4.0.5 on 2022-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0004_alter_itmonthlystatus_paymentstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTMonthlyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthName', models.CharField(max_length=20)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('action_required', 'Client Action Required'), ('quality_check', 'Quality Check'), ('done', 'Completed')], default='Pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GSTQuarterlyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=20)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('action_required', 'Client Action Required'), ('quality_check', 'Quality Check'), ('done', 'Completed')], default='Pending', max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='IncomeTaxAlert',
            new_name='TaxAlert',
        ),
    ]
