# Generated by Django 4.0.5 on 2022-07-25 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxes', '0005_gstmonthlystatus_gstquarterlystatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstmonthlystatus',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gstquarterlystatus',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itmonthlystatus',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itquarterlystatus',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxalert',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gstmonthlystatus',
            name='monthName',
            field=models.CharField(choices=[('january', 'Jan'), ('february', 'Feb'), ('march', 'Mar'), ('april', 'Apr'), ('may', 'May'), ('june', 'Jun'), ('july', 'Jul'), ('august', 'Aug'), ('september', 'Sep'), ('october', 'Oct'), ('november', 'Nov'), ('january', 'Jan-Mar'), ('april', 'Apr-Jun'), ('july', 'Jul-Sep'), ('october', 'Oct-Dec')], default='Jan', max_length=20),
        ),
        migrations.AlterField(
            model_name='gstquarterlystatus',
            name='quarter',
            field=models.CharField(choices=[], default='Jan-Mar', max_length=20),
        ),
        migrations.AlterField(
            model_name='itmonthlystatus',
            name='monthName',
            field=models.CharField(choices=[('january', 'Jan'), ('february', 'Feb'), ('march', 'Mar'), ('april', 'Apr'), ('may', 'May'), ('june', 'Jun'), ('july', 'Jul'), ('august', 'Aug'), ('september', 'Sep'), ('october', 'Oct'), ('november', 'Nov'), ('january', 'Jan-Mar'), ('april', 'Apr-Jun'), ('july', 'Jul-Sep'), ('october', 'Oct-Dec')], default='Jan', max_length=20),
        ),
        migrations.AlterField(
            model_name='itquarterlystatus',
            name='quarter',
            field=models.CharField(choices=[], default='Jan-Mar', max_length=20),
        ),
    ]
