# Generated by Django 4.0.5 on 2022-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0008_rename_monthname_gstmonthlystatus_month_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstmonthlystatus',
            name='year',
            field=models.CharField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2022, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gstquarterlystatus',
            name='year',
            field=models.CharField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2022, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itmonthlystatus',
            name='year',
            field=models.CharField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2022, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itquarterlystatus',
            name='year',
            field=models.CharField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2022, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gstmonthlystatus',
            name='month_name',
            field=models.CharField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default='Jan', max_length=20),
        ),
        migrations.AlterField(
            model_name='gstquarterlystatus',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Apr-Jun'), ('Q2', 'Jul-Sep'), ('Q3', 'Oct-Dec'), ('Q4', 'Jan-Mar')], default='Apr-Jun', max_length=20),
        ),
        migrations.AlterField(
            model_name='itmonthlystatus',
            name='month_name',
            field=models.CharField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default='Jan', max_length=20),
        ),
        migrations.AlterField(
            model_name='itquarterlystatus',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'Apr-Jun'), ('Q2', 'Jul-Sep'), ('Q3', 'Oct-Dec'), ('Q4', 'Jan-Mar')], default='Apr-Jun', max_length=20),
        ),
    ]
