# Generated by Django 4.0.5 on 2022-08-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_zoho_client_id_client_zoho_client_secret_and_more'),
        ('taxes', '0013_alter_gstmonthlystatus_month_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstmonthlystatus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='gstquarterlystatus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='itmonthlystatus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='itquarterlystatus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='taxalert',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
    ]
