# Generated by Django 4.0.5 on 2022-06-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoAccount',
            fields=[
                ('account_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('account_code', models.CharField(max_length=30)),
                ('account_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_user_created', models.BooleanField()),
                ('is_system_account', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('can_show_in_ze', models.BooleanField()),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent_account_id', models.CharField(max_length=100)),
                ('parent_account_name', models.CharField(max_length=100)),
                ('depth', models.IntegerField()),
                ('has_attachment', models.BooleanField()),
                ('is_child_present', models.BooleanField()),
                ('child_count', models.IntegerField()),
                ('created_time', models.TimeField()),
                ('is_standalone_account', models.BooleanField()),
                ('last_modified_time', models.TimeField()),
            ],
        ),
    ]
