# Generated by Django 4.0.5 on 2022-06-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_zohoaccount_child_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohoaccount',
            name='child_count',
            field=models.CharField(max_length=3),
        ),
    ]
