# Generated by Django 4.0.5 on 2022-06-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_zohoaccount_child_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zohoaccount',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='zohoaccount',
            name='last_modified_time',
        ),
    ]
