# Generated by Django 4.0.5 on 2022-06-17 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_zohoaccount_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoaccount',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zohoaccount',
            name='last_modified_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
