# Generated by Django 4.0.5 on 2022-06-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_zohoaccount_created_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoTransaction',
            fields=[
                ('categorized_transaction_id', models.CharField(max_length=30)),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_status', models.CharField(max_length=50)),
                ('transaction_status_formatted', models.CharField(max_length=50)),
                ('transaction_source', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_type_formatted', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=30)),
                ('parent_account_id', models.CharField(max_length=30)),
                ('customer_id', models.CharField(max_length=30)),
                ('payee', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('entry_number', models.CharField(max_length=50)),
                ('currency_id', models.CharField(max_length=30)),
                ('currency_code', models.CharField(max_length=20)),
                ('debit_or_credit', models.CharField(max_length=20)),
                ('offset_account_name', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fcy_debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fcy_credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reconcile_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='zohoaccount',
            name='account_for_coding',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
