# Generated by Django 4.0.5 on 2022-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_zohotransaction_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohotransaction',
            name='reconcile_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='transaction_source',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='transaction_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='transaction_status_formatted',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
