# Generated by Django 4.0.5 on 2022-06-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_zohotransaction_reconcile_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZohoTransaction',
        ),
    ]
