# Generated by Django 4.0.5 on 2022-06-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_zohotransaction_credit_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZohoTransaction',
        ),
    ]
