# Generated by Django 4.0.5 on 2022-06-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_zohotransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoTransaction',
            fields=[
                ('categorized_transaction_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=100, null=True)),
                ('transaction_status', models.CharField(max_length=50, null=True)),
                ('transaction_status_formatted', models.CharField(max_length=50, null=True)),
                ('transaction_source', models.CharField(max_length=50, null=True)),
                ('transaction_id', models.CharField(max_length=30)),
                ('transaction_date', models.DateField()),
                ('transaction_type_formatted', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=30)),
                ('parent_account_id', models.CharField(max_length=30)),
                ('customer_id', models.CharField(max_length=30)),
                ('payee', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('entry_number', models.CharField(max_length=50)),
                ('currency_id', models.CharField(max_length=30)),
                ('currency_code', models.CharField(max_length=20)),
                ('debit_or_credit', models.CharField(max_length=20)),
                ('offset_account_name', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('debit_amount', models.CharField(max_length=20, null=True)),
                ('credit_amount', models.CharField(max_length=20, null=True)),
                ('fcy_debit_amount', models.CharField(max_length=20, null=True)),
                ('fcy_credit_amount', models.CharField(max_length=20, null=True)),
                ('reconcile_status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
