# Generated by Django 4.0.5 on 2022-07-21 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_zohoaccount_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zohoaccount',
            old_name='client_id',
            new_name='client',
        ),
    ]
