# Generated by Django 4.0.5 on 2022-07-22 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_client_id_zohoaccount_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohotransaction',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.zohoaccount'),
        ),
    ]
