# Generated by Django 4.0.5 on 2022-07-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_zohotransaction_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohotransaction',
            name='account_id',
            field=models.CharField(max_length=30),
        ),
    ]
