# Generated by Django 4.0.5 on 2022-07-22 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_zohotransaction_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohotransaction',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.zohoaccount'),
        ),
    ]
