# Generated by Django 4.0.5 on 2022-07-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_zohotransaction_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zohotransaction',
            old_name='account_id',
            new_name='account',
        ),
    ]
