# Generated by Django 4.0.5 on 2022-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_account_id_zohotransaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohoaccount',
            name='account_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='account_for_coding',
            field=models.CharField(choices=[('accounts_receivable', 'Accounts Receivable'), ('advertising_and_marketing_expenses', 'Advertising and Marketing Expenses'), ('bank_balance', 'Bank Balance'), ('bank_fees_&_charges', 'Bank fees & charges'), ('brokerage_&_commission_charges', 'Brokerage & Commission Charges'), ('cash_balance', 'Cash Balance'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('depreciation_expenses', 'Depreciation expenses'), ('direct_income', 'Direct Income'), ('director_remuneration', 'Director Remuneration'), ('exchange_gain_or_loss', 'Exchange Gain or Loss'), ('indirect_income', 'Indirect Income'), ('interest_expenses', 'Interest Expenses'), ('inventories', 'Inventories'), ('it_and_internet_expenses', 'IT and Internet Expenses'), ('legal_&_professional_fees', 'Legal & Professional fees'), ('long_term_borrowings', 'Long Term Borrowings'), ('office_expenses', 'Office Expenses'), ('other_current_assets', 'Other Current Assets'), ('other_current_liabilities_&_provisions', 'Other Current Liabilities & Provisions'), ('other_employee_related_expenses', 'Other Employee related expenses'), ('other_expenses', 'Other Expenses'), ('other_liabilities', 'Other Liabilities'), ('rent_expenses', 'Rent Expenses'), ('repairs_&_maintenance_expenses', 'Repairs & Maintenance Expenses'), ('reserves_and_surplus', 'Reserves and Surplus'), ('salary_&_wages', 'Salary & Wages'), ('share_capital', 'Share Capital'), ('short_term_loans_&_advances', 'Short Term Loans & Advances'), ('short_term_borrowings', 'Short-term borrowings'), ('tangible_assets', 'Tangible Assets'), ('trade_payables', 'Trade Payables'), ('training_expenses', 'Training Expenses'), ('travel_&_hotel_stay_expenses', 'Travel & Hotel Stay Expenses'), ('uncategorized', 'Uncategorized'), ('utilities_expenses', 'Utilities Expenses')], default='accounts_receivable', max_length=50),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='can_show_in_ze',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='child_count',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='has_attachment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='is_standalone_account',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='is_system_account',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='is_user_created',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='last_modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='parent_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zohoaccount',
            name='parent_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
