# Generated by Django 4.0.5 on 2022-08-02 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0027_alter_zohoaccount_account_for_coding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_type', models.CharField(choices=[('gross_profit_margin', 'Gross Profit Margin'), ('net_profit_margin', 'Net Profit Margin'), ('return_on_equity', 'Return on Equity'), ('cashflow_to_sales_ratio', 'Cashflow to Sales Ratio'), ('working_capital_current_ratio', 'Working Capital Ratio / Current Ratio'), ('cashflow_to_debt_ratio', 'Cashflow to Debt Ratio'), ('inventory_turnover', 'Inventory turnover'), ('accounts_receivable_turnover', 'Accounts receivable turnover'), ('days_payable_outstanding', 'Days payable outstanding (DPO)'), ('debt_to_equity_ratio', 'Debt to equity ratio'), ('monthly_burn_rate', 'Monthly Burn Rate'), ('runway', 'Runway')], max_length=50)),
                ('action_need_to_be_taken', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
