# Generated by Django 4.0.5 on 2022-08-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_ratio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratio',
        ),
    ]
