# Generated by Django 4.0.5 on 2022-08-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_delete_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zohotransaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='ZohoAccount',
        ),
        migrations.DeleteModel(
            name='ZohoTransaction',
        ),
    ]
