# Generated by Django 4.0.5 on 2022-08-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zohotransaction',
            name='parent_account_id',
        ),
    ]
