# Generated by Django 4.0.5 on 2022-08-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_zohoaccount_account_for_coding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohotransaction',
            name='currency_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='currency_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='customer_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='entry_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='offset_account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='payee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='reference_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zohotransaction',
            name='transaction_type_formatted',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
