# Generated by Django 4.0.5 on 2022-08-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_client_id_client_client_and_more'),
        ('accounts', '0036_alter_ratio_client_alter_zohoaccount_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('related_table', models.CharField(choices=[('pnl', 'Income Statement'), ('balsheet', 'Balance Sheet'), ('cashflow', 'Cashflow Statement'), ('ratio', 'Ratios')], max_length=30)),
                ('note', models.TextField()),
                ('admin_response', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
    ]
