# Generated by Django 4.0.5 on 2022-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_clientnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnote',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
