# Generated by Django 4.0.5 on 2022-08-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='zoho_client_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zoho_client_secret',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zoho_organization_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zoho_redirect_uri',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zoho_refresh_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
