# Generated by Django 4.0.5 on 2022-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_zoho_client_id_client_zoho_client_secret_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zoho_redirect_uri',
        ),
        migrations.AddField(
            model_name='client',
            name='zoho_domain',
            field=models.CharField(choices=[('com', 'com'), ('in', 'in')], default='com', max_length=5),
        ),
    ]
