# Generated by Django 4.0.5 on 2022-06-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingActionable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=100)),
                ('clientRemarks', models.CharField(max_length=500)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchOutPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=100)),
                ('clientRemarks', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='PendingActionables',
        ),
        migrations.DeleteModel(
            name='WatchOut',
        ),
    ]
