# Generated by Django 4.0.5 on 2022-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pendingactionable_watchoutpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingactionable',
            name='clientRemarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='watchoutpoint',
            name='clientRemarks',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
