# Generated by Django 4.0.5 on 2022-06-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_pendingactionable_clientremarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingactionable',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
