# Generated by Django 4.0.5 on 2022-07-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_pendingactionable_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchoutpoint',
            name='clientRemarks',
        ),
    ]
