# Generated by Django 4.0.5 on 2022-07-22 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_pendingactionable_client_watchoutpoint_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_type', models.CharField(choices=[('tds', 'TDS'), ('gst', 'GST')], default='TDS', max_length=20)),
                ('compliance', models.CharField(max_length=100)),
                ('current_month_due_date', models.DateField()),
                ('current_month_status', models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('not_applicable', 'Not Applicable'), ('completed', 'Completed')], default='Not Started', max_length=20)),
                ('last_month_status', models.CharField(choices=[('not_started', 'Not Started'), ('ongoing', 'Ongoing'), ('not_applicable', 'Not Applicable'), ('completed', 'Completed')], default='Not Started', max_length=20)),
                ('last_month_completion_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
