# Generated by Django 4.0.5 on 2022-08-12 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statutorycompliance',
            old_name='current_month_due_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='dashboardaccountstatus',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='statutorycompliance',
            name='current_month_status',
        ),
        migrations.RemoveField(
            model_name='statutorycompliance',
            name='last_month_completion_date',
        ),
        migrations.RemoveField(
            model_name='statutorycompliance',
            name='last_month_status',
        ),
        migrations.AddField(
            model_name='dashboardaccountstatus',
            name='modified_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dashboardaccountstatus',
            name='period',
            field=models.DateField(default=datetime.datetime(2022, 8, 12, 6, 47, 15, 927878, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification Title', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
