# Generated by Django 4.0.5 on 2022-08-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_zoho_client_id_client_zoho_client_secret_and_more'),
        ('home', '0012_rename_current_month_due_date_statutorycompliance_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardaccountstatus',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='pendingactionable',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='statutorycompliance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
        migrations.AlterField(
            model_name='watchoutpoint',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client'),
        ),
    ]
