# Generated by Django 4.0.5 on 2022-08-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_client_id_client_client_and_more'),
        ('home', '0014_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='ClientNotification',
        ),
        migrations.CreateModel(
            name='NextDeliveryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('delivery_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.client')),
            ],
        ),
    ]
