# strings for account for codings
indirect_income = "indirect_income"
direct_income = "direct_income"
cost_of_goods_sold = "cost_of_goods_sold"
interest_expenses = "interest_expenses"
tax_expenses = "tax_expenses"
depreciation_expenses = "depreciation_expenses"
bank_balance = "bank_balance"
cash_balance = "cash_balance"
accounts_receivable = "accounts_receivable"
other_current_assets = "other_current_assets"
trade_payables = "trade_payables"
other_long_term_liabilities_and_provisions = "other_long_term_liabilities_and_provisions"
other_liabilities = "other_liabilities"
other_current_liabilities_and_provisions = "other_current_liabilities_and_provisions"
tangible_assets = "tangible_assets"
other_non_current_assets = "other_non_current_assets"
short_term_borrowings = "short_term_borrowings"
long_term_borrowings = "long_term_borrowings"
short_term_loans_and_advances = "short_term_loans_and_advances"
long_term_loans_and_advances = "long_term_loans_and_advances"
share_capital = "share_capital"

# strings for account types
income = "income"
expense = "expense"
other_expense = "other_expense"
accounts_payable = "accounts_payable"
accounts_receivable = "accounts_receivable"
bank = "bank"
cash = "cash"
equity = "equity"
fixed_asset = "fixed_asset"
long_term_liability = "long_term_liability"
other_asset = "other_asset"
other_current_asset = "other_current_asset"
other_current_liability = "other_current_liability"
other_liability = "other_liability"
stock = "stock"

# strings for time periods
current_period = "current_period"
previous_period = "previous_period"
pre_previous_period = "pre_previous_period"
current = "current"
previous = "previous"
pre_previous = "pre_prev"
three_month_avg = "three_month_avg"

# strings related to percentage
current_per = "curr_per"
previous_per = "prev_per"
per_change = "per_change"
prev_per_change = "prev_per_change"
